/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ksr.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Employee extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2075758430536404470L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Employee\",\"namespace\":\"com.ksr.avro\",\"fields\":[{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"first\",\"type\":\"string\"},{\"name\":\"last\",\"type\":\"string\"},{\"name\":\"alias\",\"type\":[\"string\",\"null\"]},{\"name\":\"age\",\"type\":[\"int\",\"null\"]},{\"name\":\"department\",\"type\":{\"type\":\"record\",\"name\":\"Department\",\"fields\":[{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"name\",\"type\":\"string\"}]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Employee> ENCODER =
      new BinaryMessageEncoder<Employee>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Employee> DECODER =
      new BinaryMessageDecoder<Employee>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Employee> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Employee> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Employee> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Employee>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Employee to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Employee from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Employee instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Employee fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private int id;
   private java.lang.CharSequence first;
   private java.lang.CharSequence last;
   private java.lang.CharSequence alias;
   private java.lang.Integer age;
   private com.ksr.avro.Department department;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Employee() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param first The new value for first
   * @param last The new value for last
   * @param alias The new value for alias
   * @param age The new value for age
   * @param department The new value for department
   */
  public Employee(java.lang.Integer id, java.lang.CharSequence first, java.lang.CharSequence last, java.lang.CharSequence alias, java.lang.Integer age, com.ksr.avro.Department department) {
    this.id = id;
    this.first = first;
    this.last = last;
    this.alias = alias;
    this.age = age;
    this.department = department;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return first;
    case 2: return last;
    case 3: return alias;
    case 4: return age;
    case 5: return department;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Integer)value$; break;
    case 1: first = (java.lang.CharSequence)value$; break;
    case 2: last = (java.lang.CharSequence)value$; break;
    case 3: alias = (java.lang.CharSequence)value$; break;
    case 4: age = (java.lang.Integer)value$; break;
    case 5: department = (com.ksr.avro.Department)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public int getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(int value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'first' field.
   * @return The value of the 'first' field.
   */
  public java.lang.CharSequence getFirst() {
    return first;
  }


  /**
   * Sets the value of the 'first' field.
   * @param value the value to set.
   */
  public void setFirst(java.lang.CharSequence value) {
    this.first = value;
  }

  /**
   * Gets the value of the 'last' field.
   * @return The value of the 'last' field.
   */
  public java.lang.CharSequence getLast() {
    return last;
  }


  /**
   * Sets the value of the 'last' field.
   * @param value the value to set.
   */
  public void setLast(java.lang.CharSequence value) {
    this.last = value;
  }

  /**
   * Gets the value of the 'alias' field.
   * @return The value of the 'alias' field.
   */
  public java.lang.CharSequence getAlias() {
    return alias;
  }


  /**
   * Sets the value of the 'alias' field.
   * @param value the value to set.
   */
  public void setAlias(java.lang.CharSequence value) {
    this.alias = value;
  }

  /**
   * Gets the value of the 'age' field.
   * @return The value of the 'age' field.
   */
  public java.lang.Integer getAge() {
    return age;
  }


  /**
   * Sets the value of the 'age' field.
   * @param value the value to set.
   */
  public void setAge(java.lang.Integer value) {
    this.age = value;
  }

  /**
   * Gets the value of the 'department' field.
   * @return The value of the 'department' field.
   */
  public com.ksr.avro.Department getDepartment() {
    return department;
  }


  /**
   * Sets the value of the 'department' field.
   * @param value the value to set.
   */
  public void setDepartment(com.ksr.avro.Department value) {
    this.department = value;
  }

  /**
   * Creates a new Employee RecordBuilder.
   * @return A new Employee RecordBuilder
   */
  public static com.ksr.avro.Employee.Builder newBuilder() {
    return new com.ksr.avro.Employee.Builder();
  }

  /**
   * Creates a new Employee RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Employee RecordBuilder
   */
  public static com.ksr.avro.Employee.Builder newBuilder(com.ksr.avro.Employee.Builder other) {
    if (other == null) {
      return new com.ksr.avro.Employee.Builder();
    } else {
      return new com.ksr.avro.Employee.Builder(other);
    }
  }

  /**
   * Creates a new Employee RecordBuilder by copying an existing Employee instance.
   * @param other The existing instance to copy.
   * @return A new Employee RecordBuilder
   */
  public static com.ksr.avro.Employee.Builder newBuilder(com.ksr.avro.Employee other) {
    if (other == null) {
      return new com.ksr.avro.Employee.Builder();
    } else {
      return new com.ksr.avro.Employee.Builder(other);
    }
  }

  /**
   * RecordBuilder for Employee instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Employee>
    implements org.apache.avro.data.RecordBuilder<Employee> {

    private int id;
    private java.lang.CharSequence first;
    private java.lang.CharSequence last;
    private java.lang.CharSequence alias;
    private java.lang.Integer age;
    private com.ksr.avro.Department department;
    private com.ksr.avro.Department.Builder departmentBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.ksr.avro.Employee.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.first)) {
        this.first = data().deepCopy(fields()[1].schema(), other.first);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.last)) {
        this.last = data().deepCopy(fields()[2].schema(), other.last);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.alias)) {
        this.alias = data().deepCopy(fields()[3].schema(), other.alias);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.age)) {
        this.age = data().deepCopy(fields()[4].schema(), other.age);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.department)) {
        this.department = data().deepCopy(fields()[5].schema(), other.department);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (other.hasDepartmentBuilder()) {
        this.departmentBuilder = com.ksr.avro.Department.newBuilder(other.getDepartmentBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing Employee instance
     * @param other The existing instance to copy.
     */
    private Builder(com.ksr.avro.Employee other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.first)) {
        this.first = data().deepCopy(fields()[1].schema(), other.first);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.last)) {
        this.last = data().deepCopy(fields()[2].schema(), other.last);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.alias)) {
        this.alias = data().deepCopy(fields()[3].schema(), other.alias);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.age)) {
        this.age = data().deepCopy(fields()[4].schema(), other.age);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.department)) {
        this.department = data().deepCopy(fields()[5].schema(), other.department);
        fieldSetFlags()[5] = true;
      }
      this.departmentBuilder = null;
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public int getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.ksr.avro.Employee.Builder setId(int value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.ksr.avro.Employee.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'first' field.
      * @return The value.
      */
    public java.lang.CharSequence getFirst() {
      return first;
    }


    /**
      * Sets the value of the 'first' field.
      * @param value The value of 'first'.
      * @return This builder.
      */
    public com.ksr.avro.Employee.Builder setFirst(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.first = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'first' field has been set.
      * @return True if the 'first' field has been set, false otherwise.
      */
    public boolean hasFirst() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'first' field.
      * @return This builder.
      */
    public com.ksr.avro.Employee.Builder clearFirst() {
      first = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'last' field.
      * @return The value.
      */
    public java.lang.CharSequence getLast() {
      return last;
    }


    /**
      * Sets the value of the 'last' field.
      * @param value The value of 'last'.
      * @return This builder.
      */
    public com.ksr.avro.Employee.Builder setLast(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.last = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'last' field has been set.
      * @return True if the 'last' field has been set, false otherwise.
      */
    public boolean hasLast() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'last' field.
      * @return This builder.
      */
    public com.ksr.avro.Employee.Builder clearLast() {
      last = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'alias' field.
      * @return The value.
      */
    public java.lang.CharSequence getAlias() {
      return alias;
    }


    /**
      * Sets the value of the 'alias' field.
      * @param value The value of 'alias'.
      * @return This builder.
      */
    public com.ksr.avro.Employee.Builder setAlias(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.alias = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'alias' field has been set.
      * @return True if the 'alias' field has been set, false otherwise.
      */
    public boolean hasAlias() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'alias' field.
      * @return This builder.
      */
    public com.ksr.avro.Employee.Builder clearAlias() {
      alias = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'age' field.
      * @return The value.
      */
    public java.lang.Integer getAge() {
      return age;
    }


    /**
      * Sets the value of the 'age' field.
      * @param value The value of 'age'.
      * @return This builder.
      */
    public com.ksr.avro.Employee.Builder setAge(java.lang.Integer value) {
      validate(fields()[4], value);
      this.age = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'age' field has been set.
      * @return True if the 'age' field has been set, false otherwise.
      */
    public boolean hasAge() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'age' field.
      * @return This builder.
      */
    public com.ksr.avro.Employee.Builder clearAge() {
      age = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'department' field.
      * @return The value.
      */
    public com.ksr.avro.Department getDepartment() {
      return department;
    }


    /**
      * Sets the value of the 'department' field.
      * @param value The value of 'department'.
      * @return This builder.
      */
    public com.ksr.avro.Employee.Builder setDepartment(com.ksr.avro.Department value) {
      validate(fields()[5], value);
      this.departmentBuilder = null;
      this.department = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'department' field has been set.
      * @return True if the 'department' field has been set, false otherwise.
      */
    public boolean hasDepartment() {
      return fieldSetFlags()[5];
    }

    /**
     * Gets the Builder instance for the 'department' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.ksr.avro.Department.Builder getDepartmentBuilder() {
      if (departmentBuilder == null) {
        if (hasDepartment()) {
          setDepartmentBuilder(com.ksr.avro.Department.newBuilder(department));
        } else {
          setDepartmentBuilder(com.ksr.avro.Department.newBuilder());
        }
      }
      return departmentBuilder;
    }

    /**
     * Sets the Builder instance for the 'department' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public com.ksr.avro.Employee.Builder setDepartmentBuilder(com.ksr.avro.Department.Builder value) {
      clearDepartment();
      departmentBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'department' field has an active Builder instance
     * @return True if the 'department' field has an active Builder instance
     */
    public boolean hasDepartmentBuilder() {
      return departmentBuilder != null;
    }

    /**
      * Clears the value of the 'department' field.
      * @return This builder.
      */
    public com.ksr.avro.Employee.Builder clearDepartment() {
      department = null;
      departmentBuilder = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Employee build() {
      try {
        Employee record = new Employee();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Integer) defaultValue(fields()[0]);
        record.first = fieldSetFlags()[1] ? this.first : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.last = fieldSetFlags()[2] ? this.last : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.alias = fieldSetFlags()[3] ? this.alias : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.age = fieldSetFlags()[4] ? this.age : (java.lang.Integer) defaultValue(fields()[4]);
        if (departmentBuilder != null) {
          try {
            record.department = this.departmentBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("department"));
            throw e;
          }
        } else {
          record.department = fieldSetFlags()[5] ? this.department : (com.ksr.avro.Department) defaultValue(fields()[5]);
        }
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Employee>
    WRITER$ = (org.apache.avro.io.DatumWriter<Employee>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Employee>
    READER$ = (org.apache.avro.io.DatumReader<Employee>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.id);

    out.writeString(this.first);

    out.writeString(this.last);

    if (this.alias == null) {
      out.writeIndex(1);
      out.writeNull();
    } else {
      out.writeIndex(0);
      out.writeString(this.alias);
    }

    if (this.age == null) {
      out.writeIndex(1);
      out.writeNull();
    } else {
      out.writeIndex(0);
      out.writeInt(this.age);
    }

    this.department.customEncode(out);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readInt();

      this.first = in.readString(this.first instanceof Utf8 ? (Utf8)this.first : null);

      this.last = in.readString(this.last instanceof Utf8 ? (Utf8)this.last : null);

      if (in.readIndex() != 0) {
        in.readNull();
        this.alias = null;
      } else {
        this.alias = in.readString(this.alias instanceof Utf8 ? (Utf8)this.alias : null);
      }

      if (in.readIndex() != 0) {
        in.readNull();
        this.age = null;
      } else {
        this.age = in.readInt();
      }

      if (this.department == null) {
        this.department = new com.ksr.avro.Department();
      }
      this.department.customDecode(in);

    } else {
      for (int i = 0; i < 6; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readInt();
          break;

        case 1:
          this.first = in.readString(this.first instanceof Utf8 ? (Utf8)this.first : null);
          break;

        case 2:
          this.last = in.readString(this.last instanceof Utf8 ? (Utf8)this.last : null);
          break;

        case 3:
          if (in.readIndex() != 0) {
            in.readNull();
            this.alias = null;
          } else {
            this.alias = in.readString(this.alias instanceof Utf8 ? (Utf8)this.alias : null);
          }
          break;

        case 4:
          if (in.readIndex() != 0) {
            in.readNull();
            this.age = null;
          } else {
            this.age = in.readInt();
          }
          break;

        case 5:
          if (this.department == null) {
            this.department = new com.ksr.avro.Department();
          }
          this.department.customDecode(in);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










